branch-defaults:
  default:
    environment: udagram-env
    group_suffix: null
deploy:
  artifact: www/deploy.zip
global:
  application_name: udagram-api
  branch: null
  default_ec2_keyname: AKIASIAP76EGVH7DDNTZ
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
