version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@2.1.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Front-End
          command: |
            npm run forntend:deploy
      - run:
          name: Deploy Back-End
          command: |
            npm run backend:deploy
      - run:
          name: SET-API-ENV
          command: |
            npm run SET-API-ENV